### PR TITLE
Adds a new parameter in List class to support index numbers.

### PR DESCRIPTION
**Pull request by rtoshiro**
Adds a new parameter in List class to support index numbers.
When this parameter is on, user can select the item using numbers (0-9) too.

### CODE REVIEW

**Comment by peter-murach** [comment]
This looks good, before I merge, would you mind fixing the specs?

**Comment by rtoshiro** [comment]
Sorry about that. I had ran rake ci before tests.... :/

**Comment by rtoshiro** [comment]
Hi @peter-murach 
Sorry about specs.
I am a little newbie in Ruby. 
Would you mind point out how can I improve "coverage"?
I understood that new "numpad" method is not coverage by spec (and other natives methods :)) but I really don't how can I test this kind of method as It depends on user interaction.
I saw the current specs but I couldn't figure this out... :(

**Comment by peter-murach** [comment]
All looks good to me, great work! I'm not bothered about coverage that much, especially about trivial accessors etc... The specs are not ideal for tseting full interactions with `select`, that's why I have examples as well to help me quickly play with what I coded up. If you feel like it, you can always add specific examples for numberered select and multi_select? I will merge later on as I'm getting ready to travel across Europe. On another note, I was thinking about the numbering and thought that we could rename the option to better express intent like `enum` that would instead of taking boolean could take delimiter, `enum: ')'`. Hence if the option is present then it means the user wants to enumerate the list. What do you think?

**Comment by rtoshiro** [comment]
Hi, Thank you.
Yes, you are right. When I developed I though about the delimiter but I had transformed into Symbol :) .
I agree that parameter is better. Yes, I like :enum more. I thought about numpad because I only had missed selecting items using keyboard numbers. And one thing took to another :)
In parallel I'm trying to understand Coverage because I have another Ruby project but I couldn't make Coverage working :)
Well. Bon Voyage. Have a good trip.

**Comment by peter-murach** [comment]
Thanks!

**Pull request merged**
